### PR TITLE
Update podspec, fix duplicate symbol issue.

### PR DESCRIPTION
**Pull request by Clifton-Roberts**
Using the podspec provided by https://github.com/Appboy/appboy-ios-sdk/commit/fdf7f349a97084488529d0eb663af69a2a76dbee (```v2.11```) results in the following build error:
```
duplicate symbol _OBJC_METACLASS_$_ABKIdentifierForAdvertisingProvider in:
    /Users/cliftonroberts/Library/Developer/Xcode/DerivedData/Lyft-gtsxagozbzknooebcotgmvkjjeqj/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-Lyft-Appboy-iOS-SDK.build/Objects-normal/x86_64/ABKIdentifierForAdvertisingProvider-C636942BD18096AE.o
duplicate symbol _OBJC_CLASS_$_ABKIdentifierForAdvertisingProvider in:
    /Users/cliftonroberts/Library/Developer/Xcode/DerivedData/Lyft-gtsxagozbzknooebcotgmvkjjeqj/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-Lyft-Appboy-iOS-SDK.build/Objects-normal/x86_64/ABKIdentifierForAdvertisingProvider-C636942BD18096AE.o
ld: 2 duplicate symbols for architecture x86_64
```

- This PR addresses the issue by changing the podspec, as suggested by one of the SDK's developers here: https://github.com/Appboy/appboy-ios-sdk/issues/24.

@matias-pequeno @Reflejo

### CODE REVIEW

**Comment by Reflejo** [comment]
Before adding any SDK to the app please let me know. We can't just keep throwing shit to it

**Comment by matias-pequeno** [comment]
@Reflejo I'll ping you re this.

**Comment by Clifton-Roberts** [comment]
@Reflejo This is purely investigative right now. We're looking at ways to implement push notification campaigns and in-app messaging. cc @derrickko @brendanlim

**Comment by matias-pequeno** [comment]
:+1:

**Pull request merged**
